# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created: Fri Jun  4 22:51:52 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(494, 321)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.applyButton = QtGui.QPushButton(self.centralwidget)
        self.applyButton.setGeometry(QtCore.QRect(360, 180, 121, 71))
        self.applyButton.setObjectName("applyButton")
        self.examineButton = QtGui.QPushButton(self.centralwidget)
        self.examineButton.setGeometry(QtCore.QRect(370, 30, 71, 24))
        self.examineButton.setObjectName("examineButton")
        self.wallpaperPathLine = QtGui.QLineEdit(self.centralwidget)
        self.wallpaperPathLine.setGeometry(QtCore.QRect(10, 30, 361, 25))
        self.wallpaperPathLine.setObjectName("wallpaperPathLine")
        self.imageLabel = QtGui.QLabel(self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(20, 70, 320, 200))
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.openBoxCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.openBoxCheckBox.setGeometry(QtCore.QRect(370, 150, 82, 23))
        self.openBoxCheckBox.setObjectName("openBoxCheckBox")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(360, 120, 121, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.optionComboBox = QtGui.QComboBox(self.centralwidget)
        self.optionComboBox.setGeometry(QtCore.QRect(360, 80, 121, 24))
        self.optionComboBox.setObjectName("optionComboBox")
        self.optionComboBox.addItem("")
        self.optionComboBox.addItem("")
        self.optionComboBox.addItem("")
        self.optionComboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 494, 23))
        self.menubar.setObjectName("menubar")
        self.menuBarHelp = QtGui.QMenu(self.menubar)
        self.menuBarHelp.setObjectName("menuBarHelp")
        self.menuBarFile = QtGui.QMenu(self.menubar)
        self.menuBarFile.setObjectName("menuBarFile")
        self.menuMode = QtGui.QMenu(self.menuBarFile)
        self.menuMode.setObjectName("menuMode")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuHelp = QtGui.QAction(MainWindow)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAbout = QtGui.QAction(MainWindow)
        self.menuAbout.setObjectName("menuAbout")
        self.menuQuit = QtGui.QAction(MainWindow)
        self.menuQuit.setObjectName("menuQuit")
        self.menuExamine = QtGui.QAction(MainWindow)
        self.menuExamine.setObjectName("menuExamine")
        self.menuOpenBox = QtGui.QAction(MainWindow)
        self.menuOpenBox.setObjectName("menuOpenBox")
        self.menuAdjust = QtGui.QAction(MainWindow)
        self.menuAdjust.setObjectName("menuAdjust")
        self.menuTiled = QtGui.QAction(MainWindow)
        self.menuTiled.setObjectName("menuTiled")
        self.menuCentered = QtGui.QAction(MainWindow)
        self.menuCentered.setObjectName("menuCentered")
        self.menuApply = QtGui.QAction(MainWindow)
        self.menuApply.setObjectName("menuApply")
        self.menuBarHelp.addAction(self.menuHelp)
        self.menuBarHelp.addAction(self.menuAbout)
        self.menuMode.addAction(self.menuAdjust)
        self.menuMode.addAction(self.menuTiled)
        self.menuMode.addAction(self.menuCentered)
        self.menuBarFile.addAction(self.menuExamine)
        self.menuBarFile.addAction(self.menuMode.menuAction())
        self.menuBarFile.addAction(self.menuOpenBox)
        self.menuBarFile.addAction(self.menuApply)
        self.menuBarFile.addSeparator()
        self.menuBarFile.addAction(self.menuQuit)
        self.menubar.addAction(self.menuBarFile.menuAction())
        self.menubar.addAction(self.menuBarHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "openWall", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.examineButton.setText(QtGui.QApplication.translate("MainWindow", "Examine", None, QtGui.QApplication.UnicodeUTF8))
        self.openBoxCheckBox.setText(QtGui.QApplication.translate("MainWindow", "autostart", None, QtGui.QApplication.UnicodeUTF8))
        self.optionComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.optionComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Adjust", None, QtGui.QApplication.UnicodeUTF8))
        self.optionComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Tiled", None, QtGui.QApplication.UnicodeUTF8))
        self.optionComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Centered", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBarHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBarFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMode.setTitle(QtGui.QApplication.translate("MainWindow", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.menuQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExamine.setText(QtGui.QApplication.translate("MainWindow", "Examine", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOpenBox.setText(QtGui.QApplication.translate("MainWindow", "OpenBox", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAdjust.setText(QtGui.QApplication.translate("MainWindow", "Adjust", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTiled.setText(QtGui.QApplication.translate("MainWindow", "Tiled", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCentered.setText(QtGui.QApplication.translate("MainWindow", "Centered", None, QtGui.QApplication.UnicodeUTF8))
        self.menuApply.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))

